### ISSUE TITLE
Crashing upon Unpacking `CoinMayhem` Mod.

### ISSUE THREAD

**Issue by NameLord** [steviegt6/tml-patcher#18]
![image](https://user-images.githubusercontent.com/27507408/132118301-a26423fa-5f65-4f40-b136-33296b40e82e.png)
And it was closing instantly the cmd.
The mod can be found on Mod browser and i don't know why is it not working.

**Comment by Steviegt6** [comment]
Open the program through a command prompt, so the window stays open after a crash and show me the actual exception.
