### ISSUE TITLE
Trouble running commands

### ISSUE THREAD

**Issue by LastChrism** [steviegt6/tml-patcher#23]
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-TML.Patcher.Client does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

I tried running a command and this came up as the output. Im not sure if its a problem with TML.Patcher but it's not working for me.

**Comment by Steviegt6** [comment]
> Could not execute because the specified command or file was not found. Possible reasons for this include:
> 
> * You misspelled a built-in dotnet command.
> * You intended to execute a .NET program, but dotnet-TML.Patcher.Client does not exist.
> * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
> 
> I tried running a command and this came up as the output. Im not sure if its a problem with TML.Patcher but it's not working for me.

Open a command prompt in the folder TML.Patcher in installed to, then run `dotnet TML.Patcher.Client.dll <command>`.
