### ISSUE TITLE
您的资源好像有些问题

### ISSUE THREAD

**Issue by miaorrren** [steviegt6/tml-patcher#25]
![SharedScreenshot](https://user-images.githubusercontent.com/106866572/171994638-54f8e057-50c0-4566-8a86-ba80b2479319.jpg)

**Comment by Steviegt6** [comment]
本消息的内容是用翻译器从英文翻译成简体中文的。

你所面临的错误不是我自己的错，你试图从一个不包含你需要运行的DLL的文件夹中运行该应用程序。请通过命令行导航到包含该应用程序的文件夹。

**Comment by steviegt6** [comment]
Closing due to a lack of follow-up information/no response.
